---
title: "Projeto BC Graficos"
author: "Econdata Analytics"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Importacao de Pacotes
```{r, message=FALSE}
library(tidyverse)
library(janitor)
library(rbcb)
library(lubridate)
library(zoo)
library(RcppRoll)
```

```{r, echo=FALSE}
start_date = "2009-12-01"

remove_end_date <- function(df){
  if("end_date" %in% colnames(df)){
    df <- df %>%
      select(-end_date)
    return(df)
  }else{
    return(df)
  }
}

inflacao <- rbcb::get_series(c("ipca" = 433,
                           "ipca_alimentacao_e_bebidas" = 1635,
                           "ipca_habitacao" = 1636,
                           "ipca_artigos_de_residencia" = 1637,
                           "ipca_vestuario" = 1638,
                           "ipca_transportes" = 1639,
                           "ipca_comunicacao" = 1640,
                           "ipca_saude_e_cuidados_pessoais" = 1641,
                           "ipca_despesas_pessoais" = 1642,
                           "ipca_educacao" = 1643,
                           "ipca_comercializaveis" = 4447,
                           "ipca_nao_comercializaveis" = 4448,
                           "ipca_monitorados" = 4449,
                           "ipca_nucleo_medias_aparadas(suavizado)" = 4466,
                           "ipca_nucleo_medias_aparadas(sem_suavizado)" = 11426,
                           "ipca_nao_duraveis" = 10841,
                           "ipca_semi_duraveis" = 10842,
                           "ipca_duraveis" = 10843,
                           "ipca_servicos" = 10844,
                           "ipca_livres" = 11428,
                           "ipca_industriais" = 27863,
                           "ipca_alimentacao_no_domicilio" = 27864,
                           "indice_de_difusao" = 21379), start_date) %>%
  reshape::merge_recurse() %>%
  remove_end_date()

ICBR <- get_series(c("ICBR" = 27574,
                     "ICBR_Agro" = 27575,
                     "ICBR_Metal" = 27576,
                     "ICBR_Energia" = 27577), start_date) %>%
  reshape::merge_recurse() %>%
  remove_end_date

ICBR_temp <- ICBR[,-1] 

n <- nrow(ICBR_temp) - 1 

m <- ncol(ICBR_temp)

variacao = data.frame()

for(i in 1:n){
  for(j in 1:m){
    taxa_variacao_ICBR <- (ICBR_temp[i+1,j]/ICBR_temp[i,j])-1
    variacao[i + 1, j] <- round(100 *taxa_variacao_ICBR, digits = 2)
  }
}

names(variacao) <- c("Tx.Var_ICBR", "Tx.Var_ICBR_Agro", "Tx.Var_ICBR_Metal", "Tx.Var_ICBR_Energia")

ICBR <- cbind(ICBR, variacao)

inflacao <- dplyr::right_join(inflacao, ICBR, by = "date")

#Setor Publico

setor_publico <- rbcb::get_series(c("Gov. Federal e BC" = 2053,
                                    "Gov. Federal" = 2054,
                                    "BC" = 2055,
                                    "Estaduais e Municipais" = 2056,
                                    "Estaduais" = 2057,
                                    "Municipais" = 2058,
                                    "Estatais" = 2059,
                                    "Estatais Federais" = 2060,
                                    "Estatais Estaduais" = 2061,
                                    "Estatais Municipais" = 2062), start_date) %>%
  reshape::merge_recurse() %>%
  remove_end_date()


setor_publico_temp <- setor_publico[,-1] 

n <- nrow(setor_publico_temp) - 1

m <- ncol(setor_publico_temp)

variacao = data.frame()

for(i in 1:n){
  for(j in 1:m){
    taxa_variacao_setor_publico <- (setor_publico_temp[i+1,j]/setor_publico_temp[i,j])-1
    variacao[i + 1, j] <- round(100 *taxa_variacao_setor_publico, digits = 2)
  }
}

names(variacao) <- c("Tx.Var_Gov. Federal e BC", "Tx.Var_Gov. Federal", "Tx.Var_BC", "Tx.Var_Estaduais e Municipais","Estaduais","Municipais","Estatais","Estatais Federais","Estatais Estaduais","Estatais Municipais")

setor_publico <- cbind(setor_publico, variacao)

#Setor Externo

setor_externo <- get_series(c("Reservas Internacionais" = 3546,
                              "Transacoes Correntes_Saldo" = 22701,
                              "Transacoes Correntes_Receita" = 22702,
                              "Transacoes Correntes_Despesa" = 22703,
                              "Conta Capital_Saldo" = 22851,
                              "Conta Capital_Receita" = 22852,
                              "Conta Capital_Despesa" = 22853,
                              "Conta Financeira" = 22863,
                              "Investimento Direto" = 23080,
                              "Dolar" = 3696), start_date) %>%
  reshape::merge_recurse()%>%
  remove_end_date()


setor_externo_temp <- setor_externo[,-1] 

n <- nrow(setor_externo_temp) - 1

m <- ncol(setor_externo_temp)

variacao = data.frame()

for(i in 1:n){
  for(j in 1:m){
    taxa_variacao_setor_externo <- (setor_externo_temp[i+1,j]/setor_externo_temp[i,j])-1
    variacao[i + 1, j] <- round(100 *taxa_variacao_setor_externo, digits = 2)
  }
}

names(variacao) <- c("Tx.Var Reservas Internacionais", 
                     "Tx.Var Transacoes Correntes_Saldo", 
                     "Tx.Var Transacoes Correntes_Receita",
                     "Tx.Var Transacoes Correntes_Despesa",
                     "Tx.Var Conta Capital_Saldo",
                     "Tx.Var Conta Capital_Receita",
                     "Tx.Var Conta Capital_Despesa",
                     "Tx.Var Conta Financeira",
                     "Tx.Var Investimento Direto",
                     "Tx.Var Dolar")

setor_externo <- cbind(setor_externo, variacao)

#Atividade

atividade <- rbcb::get_series(c("Producao Industrial" = 21859,
                                "Producao de Oleo Bruto" = 1389,
                                "Producao de LGN" = 1390,
                                "Producao Total de Derivados de Petroleo" = 1391,
                                "Producao de Gas Natural" = 1392,
                                "Consumo de Energia Eletrica - Comercial" = 1402,
                                "Consumo de Energia Eletrica - Residencial" = 1403,
                                "Consumo de Energia Eletrica - Industrial" = 1404,
                                "Consumo de Energia Eletrica - Outros" = 1405,
                                "Consumo de Energia Eletrica - Total" = 1406,
                                "Consumo de Gasolina" = 1393,
                                "Consumo de GLP" = 1394,
                                "Consumo de Oleo Combustivel" = 1395,
                                "Consumo de Oleo Diesel" = 1396,
                                "Consumo de Outros Derivados de Petroleo" = 1397,
                                "Consumo de Derivados de Petroleo - Total" = 1398,
                                "Consumo de Alcool Hidratado" = 1399,
                                "Consumo de Alcool Anidro" = 1400,
                                "Consumo de Alcool Carburante" = 1401,
                                "Volume de Vendas no Varejo" = 1455,
                                "Taxa de Desocupacao" = 24369,
                                "IVGR" = 21340,
                                "IBCBR" = 24363), start_date) %>%
  reshape::merge_recurse() %>%
  remove_end_date()


atividade_temp <- atividade[,-1] 

n <- nrow(atividade_temp) - 1

m <- ncol(atividade_temp)

variacao = data.frame()

for(i in 1:n){
  for(j in 1:m){
    taxa_variacao_atividade <- (atividade_temp[i+1,j]/atividade_temp[i,j])-1
    variacao[i + 1, j] <- round(100 *taxa_variacao_atividade, digits = 2)
  }
}

names(variacao) <- c("Tx.Var Producao Industrial", 
                     "Tx.Var Producao de Oleo Bruto", 
                     "Tx.Var Producao de LGN",
                     "Tx.Var Producao Total de Derivados de Petroleo",
                     "Tx.Var Producao de Gas Natural",
                     "Tx.Var Consumo de Energia Eletrica - Comercial",
                     "Tx.Var Consumo de Energia Eletrica - Residencial",
                     "Tx.Var Consumo de Energia Eletrica - Industrial",
                     "Tx.Var Consumo de Energia Eletrica - Outros",
                     "Tx.Var Consumo de Energia Eletrica - Total",
                     "Tx.Var Consumo de Gasolina",
                     "Tx.Var Consumo de GLP",
                     "Tx.Var Consumo de Oleo Combustivel",
                     "Tx.Var Consumo de Oleo Diesel",
                     "Tx.Var Consumo de Outros Derivados de Petroleo",
                     "Tx.Var Consumo de Derivados de Petroleo - Total",
                     "Tx.Var Consumo de Alcool Hidratado",
                     "Tx.Var Consumo de Alcool Anidro",
                     "Tx.Var Consumo de Alcool Carburante",
                     "Tx.Var Volume de Vendas no Varejo",
                     "Tx.Var da Taxa de Desocupacao",
                     "Tx.Var IVG-R",
                     "Tx.Var IBC-BR")

atividade <- cbind(atividade, variacao)

atividade <- atividade %>%
  clean_names()

inflacao <- inflacao %>%
  clean_names()

setor_externo <- setor_externo %>% 
  clean_names()

setor_publico <- setor_publico %>%
  clean_names()
```

## Inflacao

```{r, echo=FALSE, warning=FALSE}
inflacao_atual <- inflacao %>%
  select(1:11) %>%
  pivot_longer(-c(date, ipca), names_to = "Tipo", values_to = "Valores")

inf_temp <- inflacao %>% select(1:11)
names(inf_temp) <- c("date", "IPCA","Aliment. e Beb.","Habitacao","Art. de Resid.","Vestuario","Transportes",
                     "Comunicacao","Saude","Desp. Pessoais","Educacao")
inf_temp <- inf_temp %>%
  pivot_longer(-date, names_to = "Tipo", values_to = "Valores") 

inflacao <- inflacao %>%
  mutate(ipca_alimentos = ipca_livres - ((37.22/74.91) * ipca_servicos) - ((24.59/74.91) * ipca_industriais)) %>%
  mutate(ipca = roll_prodr(1 + (ipca/100), n = 12L, fill = NA) - 1,
           ipca_alimentacao_e_bebidas = roll_prodr(1 + (ipca_alimentacao_e_bebidas/100), n = 12, fill = NA) - 1,
           ipca_habitacao = roll_prodr(1 + (ipca_habitacao/100), n = 12, fill = NA) - 1,
           ipca_artigos_de_residencia = roll_prodr(1 + (ipca_artigos_de_residencia/100), n = 12, fill = NA) - 1,
           ipca_vestuario = roll_prodr(1 + (ipca_vestuario/100), n = 12, fill = NA) - 1,
           ipca_transportes = roll_prodr(1 + (ipca_transportes/100), n = 12, fill = NA) - 1,
           ipca_comunicacao = roll_prodr(1 + (ipca_comunicacao/100), n = 12, fill = NA) - 1,
           ipca_saude_e_cuidados_pessoais = roll_prodr(1 + (ipca_saude_e_cuidados_pessoais/100), n = 12, fill = NA) - 1,
           ipca_despesas_pessoais = roll_prodr(1 + (ipca_despesas_pessoais/100), n = 12, fill = NA) - 1,
           ipca_educacao = roll_prodr(1 + (ipca_educacao/100), n = 12, fill = NA) - 1,
           ipca_comercializaveis = roll_prodr(1 + (ipca_comercializaveis/100), n = 12, fill = NA) - 1,
           ipca_nao_comercializaveis = roll_prodr(1 + (ipca_nao_comercializaveis/100), n = 12, fill = NA) - 1,
           ipca_monitorados = roll_prodr(1 + (ipca_monitorados/100), n = 12, fill = NA) - 1,
           ipca_nucleo_medias_aparadas_suavizado = roll_prodr(1 + (ipca_nucleo_medias_aparadas_suavizado/100), n = 12, fill = NA) - 1,
           ipca_nucleo_medias_aparadas_sem_suavizado = roll_prodr(1 + (ipca_nucleo_medias_aparadas_sem_suavizado/100), n = 12, fill = NA) - 1,
           ipca_nao_duraveis = roll_prodr(1 + (ipca_nao_duraveis/100), n = 12, fill = NA) - 1,
           ipca_semi_duraveis = roll_prodr(1 + (ipca_semi_duraveis/100), n = 12, fill = NA) - 1,
           ipca_duraveis = roll_prodr(1 + (ipca_duraveis/100), n = 12, fill = NA) - 1,
           ipca_servicos = roll_prodr(1 + (ipca_servicos/100), n = 12, fill = NA) - 1,
           ipca_livres = roll_prodr(1 + (ipca_livres/100), n = 12, fill = NA) - 1,
           ipca_industriais = roll_prodr(1 + (ipca_industriais/100), n = 12, fill = NA) - 1,
           ipca_alimentacao_no_domicilio = roll_prodr(1 + (ipca_alimentacao_no_domicilio/100), n = 12, fill = NA) - 1,
           ipca_alimentos = roll_prodr(1 + (ipca_alimentos/100), n = 12, fill = NA) - 1)


inflacao_atual_12 <- inflacao %>%
  select(1:11) %>%
  pivot_longer(-c(date, ipca), names_to = "Tipo", values_to = "Valores")

icbr <- inflacao %>% select(1, 25:28) %>%
  pivot_longer(-date,
               names_to = "Tipo",
               values_to = "Valores")

icbr %>% ggplot(aes(x = date, y = Valores, color = Tipo)) +
  geom_line() +
  scale_x_date(date_labels = "%b/%Y",
               breaks = scales::pretty_breaks(10))  +
  scale_y_continuous(breaks = scales::pretty_breaks(5)) +
  labs(x = "", y = "Valores", title = "ICBR", subtitle = "Desagregações ICBR",
                       caption = "Econdata Analytics, fonte: BCB", colour = "") +
  scale_color_manual(values = c("icbr" = "dark blue",
                                "icbr_agro" = "red",
                                "icbr_energia" = "purple",
                                "icbr_metal" = "green"), labels = c("ICBR", "IBR Agro", "ICBR Energia", "ICBR Metal")) +
  theme_minimal()+
  theme(plot.title = element_text(size = 18,
                                  face = "bold"),
        legend.position = "bottom") 

inflacao_atual_12 %>% filter(year(date) >= 2020) %>% ggplot(aes(x = month(date), y = Valores, fill = Tipo))+
  geom_col() +
  facet_grid(rows = vars(year(date))) +
  scale_y_continuous(breaks = scales::pretty_breaks(4)) +
  labs(x = "Meses", y = "Valores", title = "IPCA", subtitle = "Desagregações IPCA acumulado 12 meses",
       caption = "Econdata Analytics, fonte: BCB", fill = "") +
  scale_fill_manual(values = c("ipca_alimentacao_e_bebidas" = "green",
                               "ipca_artigos_de_resid_ncia" = "red",
                               "ipca_comunicacao" = "purple",
                               "ipca_despesas_pessoais" = "#572C00",
                               "ipca_educacao" = "#00FFFF",
                               "ipca_habitacao" = "blue",
                               "ipca_saude_e_cuidados_pessoais" = "orange",
                               "ipca_transportes" = "#017901",
                               "ipca_vestuario" = "magenta"), labels = c("Alimentacao e Bebidas",
                                                                         "Art. de Residencia",
                                                                         "Comunicacao", 
                                                                         "Desp. Pessoais",
                                                                         "Educacao",
                                                                         "Habitacao",
                                                                         "Saude",
                                                                         "Transportes",
                                                                         "Vestuario")) +
  scale_x_continuous(
    breaks = seq_along(month.name), 
    labels = month.name
  ) +
  theme_minimal() + 
  geom_hline(yintercept=0, linetype="dashed", color = "black") +
  theme(plot.title = element_text(size = 18,
                                  face = "bold"),
        legend.position = "bottom",
        axis.text.x.bottom = element_text(size = 6.5))

inflacao_atual_12 %>% ggplot(aes(x = date, y = Valores, color = Tipo))+
  geom_line()  +
  scale_y_continuous(breaks = scales::pretty_breaks(3))  +
  scale_x_date(date_labels = "%b/%Y",
               breaks = scales::pretty_breaks(10)) +
  labs(x = "", y = "Valores", title = "IPCA", subtitle = "Desagregações IPCA acumulado 12 meses",
       caption = "Econdata Analytics, fonte: BCB", colour = "") +
  scale_color_manual(values = c("ipca" = "dark blue",
                                "ipca_alimentacao_e_bebidas" = "green",
                               "ipca_artigos_de_resid_ncia" = "red",
                               "ipca_comunicacao" = "purple",
                               "ipca_despesas_pessoais" = "#572C00",
                               "ipca_educacao" = "#00FFFF",
                               "ipca_habitacao" = "blue",
                               "ipca_saude_e_cuidados_pessoais" = "orange",
                               "ipca_transportes" = "#017901",
                               "ipca_vestuario" = "magenta"),labels = c("IPCA", 
                                                                         "Alimentacao e Bebidas",
                                                                         "Art. de Residencia",
                                                                         "Comunicacao", 
                                                                         "Desp. Pessoais",
                                                                         "Educacao",
                                                                         "Habitacao",
                                                                         "Saude",
                                                                         "Transportes",
                                                                         "Vestuario")) +
  theme_minimal() +
  theme(plot.title = element_text(size = 18,
                                  face = "bold"),
        legend.position = "bottom",
        legend.text = element_text(size = 8))

inf_temp %>% filter(year(date) >= 2018) %>% ggplot(aes(x = month(date), y = Valores, color = Tipo))+
  geom_line() +
  facet_grid(rows = vars(year(date)),
             cols = vars(Tipo)) +
  scale_y_continuous(breaks = scales::pretty_breaks(3)) +
  scale_x_continuous(breaks = scales::pretty_breaks(4)) +
  labs(x = "Meses", y = "Valores", title = "IPCA", subtitle = "Desagregações IPCA (variações mensais)",
       caption = "Econdata Analytics, fonte: BCB", colour = "") +
  scale_color_manual(values = c("IPCA" = "dark blue",
                                "Aliment. e Beb." = "green",
                                "Art. de Resid." = "red",
                                "Comunicacao" = "purple",
                                "Desp. Pessoais" = "#572C00",
                                "Educacao" = "#00FFFF",
                                "Habitacao" = "blue",
                                "Saude" = "orange",
                                "Transportes" = "#017901",
                                "Vestuario" = "magenta"),labels = c("IPCA", 
                                                                         "Alimentacao e Bebidas",
                                                                         "Artigos de Residencia",
                                                                         "Comunicacao", 
                                                                         "Despesas Pessoais",
                                                                         "Educacao",
                                                                         "Habitacao",
                                                                         "Saude",
                                                                         "Transportes",
                                                                         "Vestuario")) +
  theme_minimal()  +
  theme(plot.title = element_text(size = 18,
                                  face = "bold"),
        legend.position = "bottom",
        legend.text = element_text(size = 8),
        strip.text.x = element_text(size = 5))

inflacao %>% 
  ggplot(aes(x = date, y = indice_de_difusao)) +
  geom_col(fill = "blue", color = "black") +
  scale_x_date(date_labels = "%B/%Y",
               breaks = scales::pretty_breaks(5)) +
  labs(x = "", y = "Índice de Difusão", title = "Índice de Difusão da Inflação (em %)",
       caption = "Econdata Analytics, fonte: BCB", colour = "") +
  coord_cartesian(ylim=c(40, 80)) +
  theme_minimal() +
  theme(plot.title = element_text(size = 18,
                                  face = "bold"),
        legend.position = "bottom")

inflacao %>%
  ggplot(aes(x = date, y = indice_de_difusao)) +
  geom_line(color = "blue") +
  scale_x_date(date_labels = "%B/%Y",
               breaks = scales::pretty_breaks(5)) +
  labs(x = "", y = "Índice de Difusão", title = "Índice de Difusão da Inflação (em %)",
       caption = "Econdata Analytics, fonte: BCB", colour = "") +
  coord_cartesian(ylim=c(40, 80)) +
  theme_minimal() +
  theme(plot.title = element_text(size = 18,
                                  face = "bold"),
        legend.position = "bottom")

ipca_duraveis <- inflacao %>% select(1, 2, 17:19) %>% pivot_longer(-date, names_to = "Tipo", values_to = "Valores")

ipca_duraveis %>%
  ggplot(aes(x = date, y = Valores, color = Tipo)) +
  geom_line() +
  scale_x_date(date_labels = "%B/%Y",
               breaks = scales::pretty_breaks(5)) +
  labs(x = "", y = "Valores", title = "IPCA e Bens Duráveis", subtitle = "Acumulado 12 meses",
       caption = "Econdata Analytics, fonte: BCB", colour = "") +
  scale_color_manual(values = c("ipca" = "dark blue",
                                "ipca_nao_duraveis" = "red",
                                "ipca_semi_duraveis" = "green",
                                "ipca_duraveis" = "orange"),
                     labels = c("IPCA",
                                "Não Duráveis",
                                "Semi Duráveis",
                                "Duráveis")) +
  theme_minimal() +
  theme(plot.title = element_text(size = 18,
                                  face = "bold"),
        legend.position = "bottom")
  
ipca_subgrupos <- inflacao %>% select(1,2, 20:22) %>% pivot_longer(-date, names_to = "Tipo", values_to = "Valores")

ipca_subgrupos %>% 
  ggplot(aes(x = date, y = Valores, color = Tipo)) +
  geom_line() +
  scale_x_date(date_labels = "%B/%Y",
               breaks = scales::pretty_breaks(5)) +
  labs(x = "", y = "Valores", title = "IPCA e SubGrupos", subtitle = "Acumulado 12 meses",
       caption = "Econdata Analytics, fonte: BCB", colour = "") +
  scale_color_manual(values = c("ipca" = "dark blue",
                                "ipca_industriais" = "red",
                                "ipca_livres" = "green",
                                "ipca_servicos" = "orange"),
                     labels = c("IPCA",
                                "Industriais",
                                "Livres",
                                "Serviços")) +
  theme_minimal() +
  theme(plot.title = element_text(size = 18,
                                  face = "bold"),
        legend.position = "bottom")

ipca_comercializaveis <- inflacao %>% select(1:2, 12:13) %>%
  pivot_longer(-date, names_to = "Tipo", values_to = "Valores") 


ipca_comercializaveis %>%
  ggplot(aes(x = date, y = Valores, color = Tipo)) +
  geom_line() +
  scale_x_date(date_labels = "%Y",
               breaks = scales::pretty_breaks(3)) +
  labs(x = "", y = "Valores", title = "IPCA Comercializáveis", subtitle = "Acumulado 12 meses",
       caption = "Econdata Analytics, fonte: BCB", colour = "") +
  theme(plot.title = element_text(size = 18,
                                  face = "bold")) +
  scale_color_manual(values = c("ipca" = "dark blue",
                                "ipca_comercializaveis" = "red",
                                "ipca_nao_comercializaveis" = "green"),
                     labels = c("IPCA",
                                "Comercializáveis",
                                "Não Comercializáveis")) +
  theme_minimal() +
  theme(plot.title = element_text(size = 18,
                                  face = "bold"),
        legend.position = "bottom")


ipca_nucleo <- inflacao %>% select(1, 15, 16) %>%
  pivot_longer(-date, names_to = "Tipo", values_to = "Valores") 

ipca_nucleo %>% 
  ggplot(aes(x = date, y = Valores, color = Tipo)) +
  geom_line() +
  scale_x_date(date_labels = "%B/%Y",
               breaks = scales::pretty_breaks(5)) +
  labs(x = "", y = "Valores", title = "Núcleos de Inflação", subtitle = "Acumulado 12 meses",
       caption = "Econdata Analytics, fonte: BCB", colour = "") +
  theme(plot.title = element_text(size = 18,
                                  face = "bold")) +
  scale_color_manual(values = c("ipca_nucleo_medias_aparadas_suavizado" = "red",
                                "ipca_nucleo_medias_aparadas_sem_suavizado" = "green"),
                     labels = c("Núcleo Médias Aparadas(suavizado)",
                                "Núcleo Médias Aparadas(sem suavizado)")) +
  theme_minimal() +
  theme(plot.title = element_text(size = 18,
                                  face = "bold"),
        legend.position = "bottom")

```

## Atividade

```{r, echo=FALSE, warning=FALSE}
plot_titles = data.frame(titles = c("Produção Industrial",
                                    "Produção de Óleo Bruto",
                                    "Produção de LGN",
                                    "Produção Total de Derivados de Petróleo",
                                    "Produção de Gas Natural",
                                    "Consumo de Energia Elétrica - Comercial",
                                    "Consumo de Energia Elétrica - Residencial",
                                    "Consumo de Energia Elétrica - Industrial",
                                    "Consumo de Energia Elétrica - Outros",
                                    "Consumo de Energia Elétrica - Total",
                                    "Consumo de Gasolina",
                                    "Consumo de GLP",
                                    "Consumo de Oleo Combustivel",
                                    "Consumo de Oleo Diesel",
                                    "Consumo de Outros Derivados de Petroleo",
                                    "Consumo de Derivados de Petróleo - Total",
                                    "Consumo de Álcool Hidratado",
                                    "Consumo de Álcool Anidro",
                                    "Consumo de Álcool Carburante",
                                    "Volume de Vendas no Varejo",
                                    "Taxa de Desocupação",
                                    "IVGR",
                                    "IBCBR"),
                         unidades = c("",
                                      "Barris/dia (mil)",
                                      "Barris/dia (mil)",
                                      "Barris/dia (mil)",
                                      "Barris/dia (mil)",
                                      "GWh",
                                      "GWh",
                                      "GWh",
                                      "GWh",
                                      "GWh",
                                      "Barris/dia (mil)",
                                      "Barris/dia (mil)",
                                      "Barris/dia (mil)",
                                      "Barris/dia (mil)",
                                      "Barris/dia (mil)",
                                      "Barris/dia (mil)",
                                      "Barris/dia (mil)",
                                      "Barris/dia (mil)",
                                      "Barris/dia (mil)",
                                      "",
                                      "%",
                                      "",
                                      ""))
for (i in 1:23){
  print(
    ggplot(data = atividade)+
    geom_line(aes(x = date, y = atividade[,i]), colour = "#021b3d", size = 0.7)+
    xlab("")+ylab(as.character(plot_titles[i,2]))+
    ggtitle(as.character(plot_titles[i,1]))+
    theme_bw()+
      labs(caption = "Econdata Analytics, fonte: BCB") +
    theme(plot.title = element_text(family='sans',hjust = 0.5,colour='#002060',size=13,face='bold'),
          axis.title.x = element_text(family="sans",color="cornsilk4", size=8),
          panel.border = element_blank(), panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))+
    scale_y_continuous(labels = scales::comma)
  )
}
```

## Setor Publico

```{r, echo=FALSE}
setor_publico %>%
  ggplot()+
  geom_line(aes(x = date, y = gov_federal), color = 'blue')+
  geom_rect(aes(xmin = as.Date('01/04/2014', format = '%d/%m/%Y'),
                xmax = as.Date('01/10/2016', format = '%d/%m/%Y'),
                ymin = -Inf,
                ymax = Inf), alpha = 0.005)+
  geom_rect(aes(xmin = as.Date('01/01/2020', format = '%d/%m/%Y'),
                xmax = as.Date('01/10/2021', format = '%d/%m/%Y'),
                ymin = -Inf,
                ymax = Inf), alpha = 0.005)+
  theme_classic()+
  labs(x = '',
       y = 'Reais',
       caption = 'Econdata Analytics, Fonte: Banco Central e CODACE',
       title = 'Dívida Líquida do Governo Federal e Recessões Brasileiras')

setor_publico %>%
  ggplot()+
  geom_line(aes(x = date, y = bc), color = 'blue')+
  geom_rect(aes(xmin = as.Date('01/04/2014', format = '%d/%m/%Y'),
                xmax = as.Date('01/10/2016', format = '%d/%m/%Y'),
                ymin = -Inf,
                ymax = Inf), alpha = 0.005)+
  geom_rect(aes(xmin = as.Date('01/01/2020', format = '%d/%m/%Y'),
                xmax = as.Date('01/10/2021', format = '%d/%m/%Y'),
                ymin = -Inf,
                ymax = Inf), alpha = 0.005)+
  theme_classic()+
  labs(x = '',
       y = 'Reais',
       caption = 'Econdata Analytics, Fonte: Banco Central e CODACE',
       title = 'Dívida Líquida do Banco Central e Recessões Brasileiras')

setor_publico %>%
  ggplot()+
  geom_line(aes(x = date, y = estaduais_e_municipais), color = 'blue')+
  geom_rect(aes(xmin = as.Date('01/04/2014', format = '%d/%m/%Y'),
                xmax = as.Date('01/10/2016', format = '%d/%m/%Y'),
                ymin = -Inf,
                ymax = Inf), alpha = 0.005)+
  geom_rect(aes(xmin = as.Date('01/01/2020', format = '%d/%m/%Y'),
                xmax = as.Date('01/10/2021', format = '%d/%m/%Y'),
                ymin = -Inf,
                ymax = Inf), alpha = 0.005)+
  theme_classic()+
  labs(x = '',
       y = 'Reais',
       caption = 'Econdata Analytics, Fonte: Banco Central e CODACE',
       title = 'Dívida Líquida de Estados e Municípios e Recessões Brasileiras')

setor_publico %>%
  ggplot()+
  geom_line(aes(x = date, y = estatais), color = 'blue')+
  geom_rect(aes(xmin = as.Date('01/04/2014', format = '%d/%m/%Y'),
                xmax = as.Date('01/10/2016', format = '%d/%m/%Y'),
                ymin = -Inf,
                ymax = Inf), alpha = 0.005)+
  geom_rect(aes(xmin = as.Date('01/01/2020', format = '%d/%m/%Y'),
                xmax = as.Date('01/10/2021', format = '%d/%m/%Y'),
                ymin = -Inf,
                ymax = Inf), alpha = 0.005)+
  theme_classic()+
  labs(x = '',
       y = 'Reais',
       caption = 'Econdata Analytics, Fonte: Banco Central e CODACE',
       title = 'Dívida Líquida de Estatais e Recessões Brasileiras')

```

